config/routes.rb
Rails.application.routes.draw do



  resources :line_items
  resources :carts
  get 'signup', to: "users#new"
  get 'login', to: "sessions#new", as: "login"
  post 'login', to: "sessions#create" 
  get 'logout', to: "sessions#destroy", as: "logout"

  root to: "welcome#index"

  resources :user_stocks, only: [:create, :destroy]
  resources :users 
  resources :friendships
  
  get 'search_users', to: "users#search_users"
  get 'my_friends', to: "users#my_friends"
  get 'search_stocks', to: "stocks#search"
  get 'portfolio', to: "users#portfolio"
  post 'add_friend', to: "users#add_friend" 

  mount ActionCable.server, at: '/cable'

  get 'chat', to: "chatroom#index", as: "chatroom"

  post 'message', to: "messages#create"

end 

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController 
    def index 
        @message = Message.new 
        @messages = Message.all
    end 
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/views/chatroom/index.html.erb
<h1 align="center">Stock Chat</h1> 
<div id="scroll">
  <div class="container" id='message-container'>
      <%= render @messages %>
  </div> 
</div> 

<br>
<br>
<div class="container"> 
    <h2>Add Your Comments Below:</h2>
    <%= form_for(@message, url: message_path, remote: true) do |t| %>
        <div class="mb-3">
            <%= t.text_field :body, class: "form-control" %> <%= t.submit class: ".form-button btn btn-primary float-right" %>
        <div> 
    <% end %> 
</div> 