config/routes.rb
Rails.application.routes.draw do



  resources :line_items
  resources :carts
  get 'signup', to: "users#new"
  get 'login', to: "sessions#new", as: "login"
  post 'login', to: "sessions#create" 
  get 'logout', to: "sessions#destroy", as: "logout"

  root to: "welcome#index"

  resources :user_stocks, only: [:create, :destroy]
  resources :users 
  resources :friendships
  
  get 'search_users', to: "users#search_users"
  get 'my_friends', to: "users#my_friends"
  get 'search_stocks', to: "stocks#search"
  get 'portfolio', to: "users#portfolio"
  post 'add_friend', to: "users#add_friend" 

  mount ActionCable.server, at: '/cable'

  get 'chat', to: "chatroom#index", as: "chatroom"

  post 'message', to: "messages#create"

end 

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :remember_token 
    has_many :messages 
    has_many :friendships
    has_many :friends, through: :friendships
    has_many :user_stocks, dependent: :destroy
    has_many :stocks, through: :user_stocks 
    
    has_secure_password
    
    validates :name, :username, :email, presence: true
    validates :username, uniqueness: true
    validates :email, length: { minimum: 8 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, length: { maximum: 100 }, 
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }
            
    def self.search_by_email(email)
         where("email LIKE ?", "%#{email}%") 
         begin
            user = User.find_by(email: email)
            new(name: user.name, email: user.email, username: user.username)
         rescue Exception => e
            return nil
            
         end
    end 

    def self.youbank_welcome(name) 
        user = User.find_by(name: name) 
        "#{user}! #{YouBank.welcome}"
    end 
    
    def self.search_by_name(name)
        where("name LIKE ?", "%#{name}%")
        begin
            user = User.find_by(name: name)
            new(name: user.name, email: user.email, username: user.username)
        rescue Exception => e
            return nil
        end
    
    end
    
    def self.search_by_username(username)
        where("username LIKE ?", "%#{username}%")
        begin
            user = User.find_by(username: username)
            new(name: user.name, email: user.email, username: user.username)
        rescue Exception => e
            return nil
        end
    end
    
    def stock_added?(ticker)
        stock = Stock.find_by_ticker(ticker)
        return false unless stock
        user_stocks.where(stock_id: stock.id).exists?
    end
    
    def under_stock_limit?
        (user_stocks.count < 10)
    end
    
    def can_add_stock?(ticker)
        under_stock_limit? && !stock_added?(ticker)
    end 

    def stock_purchase_price(ticker, quantity) 
        stock = Stock.find_by_ticker(ticker)
        total_price = stock.latest_price * quantity 
        total_price
    end
    
    def self.search(param)
        cleaned_param = clean_parameter(param)
        result = (match_name(param) + match_username(param) +
                 match_email(param)).uniq
        return nil unless result
        result
    end

    def self.clean_parameter(param)
        param.strip!
        param.downcase!
    end
    
    #try to combione match_* methods below into 1 method 

    def self.match_name(name)
        self.where("name LIKE ?", "%#{name}%")
    end
    
    def self.match_email(email)
        self.where("email LIKE ?", "%#{email}%")
    end
    
    def self.match_username(username)
        self.where("username LIKE ?", "%#{username}%")
    end
    
    
    
    def not_yet_friends?(user)
        friendships.where(friend_id: user).count < 1
    end
    
    def User.digest(string)
        Digest::SHA2.hexdigest(string)
    end
    
    
    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    if params[:email]
      @user = User.search_by_email(params[:email])
    elsif params[:name]
      @user = User.search_by_name(params[:name])
    elsif params[:username]
      @user = User.search_by_username(params[:username])
    else
      @users = User.all
    end
    
      @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @friendships = @user.friends
  end
  
  def new
    @user = User.new
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Account successfully created!"
      log_in(@user) 
      UserSignupMailer.send_signup_email(@user).deliver
      redirect_to user_path(@user)
    else
      flash[:danger] = "Woops! Try again!"
      render :new
    end
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      flash[:success] = "User successfully updated!"
      redirect_to users_path
    else
      flash[:danger] = "Woops!. Try again!"
      render :edit
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    if @user.destroy
      flash[:success] = "User successfully removed!"
      session[:user_id] = nil
      redirect_to root_path
    end
  end
  
  def my_friends
    @friendships = current_user.friends
    
  end
  
  def search_users 
    if params[:potential_friend].present? 
      @user = User.search(params[:potential_friend])
      if @user 
        respond_to do |format| 
          flash[:success] = "User found!"
          format.js { render partial: 'users/friend_result' } 
        end 
      else 
        flash[:danger] = "Please enter valid user" 
        redirect_to my_friends_path 
      end 
    else 
      flash[:alert] = "User name cannot be blank!" 
      redirect_to my_friends_path 
    end 
  end 

  def search_usersss
    if params[:potential_friend].blank?
      flash.now[:danger] = "Field cannot be blank"
      render 'users/my_friends'
    else
      @user = User.search(params[:potential_friend])
      flash.now[:danger] = "User not found" if @user.blank? 
      if @user 
        respond_to do |format| 
          flash[:success] = "#{@user} found!"
          format.js { render partial: 'users/friend_result' } 
        end 
      else 
        flash[:success] = "Enter valid user"
        redirect_to my_friends_path
      end
    end
  end 

  def add_friend
    friend = User.find(params[:friend])
    current_user.friendships.build(friend_id: friend.id) 
    friend.friendships.build(friend_id: current_user.id)
    if current_user.save && friend.save
      flash[:success] = "Friend successfully added" 
      redirect_to users_path
    else
      flash[:danger] = "Woops!. An error has occurred" 
      redirect_to users_path
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :balance, :username, :search)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_friend_result.html.erb
<% if @user %> 
    <h3><%= @user.first.name %></h3> 
    <h3><%= @user.first.email %></h3> 
    <% if logged_in? %>
                <% if current_user.not_yet_friends?(@user.first.id) %>
                    <td><%= link_to "Add Friend", add_friend_path(user: current_user, friend: @user.first), 
                            method: :post, class: "btn btn-success" %></td>
                <% else %>
                    <td><%= link_to "Already Friends!", user_path(@user.first) %></td>
                <% end %>
            <% end %> 
<% end %> 

app/views/users/_friend_result.js.erb
document.querySelector('#friend-result').innerHTML = '<%= escape_javascript(render 'users/friend_result.html') %>'

app/views/users/_friends.html.erb
<% if @friendships.count > 0 %>
    <h1>My Friends</h1> 
    <table align="center" class="table table-striped col-md-6">
        <% @friendships.each do |friend| %>
            <tr>
                <td><%= link_to friend.name, user_path(friend) %></td>
                <td><%= friend.email %></td> 
                <td><%= link_to "Remove Friend", friendship_path(friend), method: :delete, data: { confirm: "Are you sure?" } %> 
            </tr>
        <% end %>
    </table>
<% else %>
    <h3>You have no friends yet</h3> 
    <h3>Let's make some friends!</h3>
<% end %>

app/views/users/_list_stocks.html.erb
<div class="col-9 mx-auto"> 
            <table align="center" class="table table-striped">
                <tr>
                    <th>Company Name</th>
                    <th>Ticker Symbol</th>
                    <th>Latest Price</th>
                    <th>Remove Stock</th>
                </tr>
                
                <% @user.stocks.each do |stock| %>
                    <tr>
                        <td><%= stock.name %></td>
                        <td><%= stock.ticker %></td>
                        <td><%= stock.last_price %></td>
                        <td><%= link_to "Remove Stock", user_stock_path(stock), 
                                method: :delete, data: { confirm: "Are you sure?" } %></td>
                    </tr>
                <% end %>
                <%= link_to "Find More Stocks", search_stocks_path %>
            </table>  
        </div> 

app/views/users/_list_users.html.erb
<table align="center" class="table table-striped">
    <tr>
            <th>User Id</th>
            <th>Username</th>
            <th>Name</th>
            <th>Email</th>
    </tr>
    <% @users.each do |user| %>
        
        <tr>
            <td><%= user.id %></td>
            <td><%= link_to user.username, user_path(user) %></td>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <% if logged_in? %>
                <% if current_user.not_yet_friends?(user.id) %>
                    <td><%= link_to "Add Friend", add_friend_path(user: current_user, friend: user), 
                            method: :post, class: "btn btn-success" %></td>
                <% else %>
                    <td><%= link_to "Already Friends!", user_path(user) %></td>
                <% end %>
            <% end %>
        </tr>
    <% end %>
</table>

app/views/users/_stock_result.html.erb
<% if @stock %>
    <h3>Name: <%= @stock.name %></h3>
    <h3>Ticker: <%= @stock.ticker %></h3>
    <h3>Latest Price: <%= @stock.last_price %></h3>
    <h3>Market Capitalization: <%= @stock.market_cap %></h3>
    <h4>Sector: <%= @stock.sector %></h4>
    <h4>Daily High: <%= @stock.high %></h4>
    <h4>Daily Low: <%= @stock.low %></h4>
    <h4>PE Ratio: <%= @stock.pe_ratio %></h4>
    <h4>YTD Change: <%= @stock.ytd_change %></h4>
    <% if current_user.can_add_stock?(@stock.ticker) %>
        <h3><%= link_to 'Add Stock', user_stocks_path(user: current_user, stock_ticker: @stock.ticker), class: "btn btn-primary", method: :post %></h3>
    <% else %>
        <h3>Cannot add Stock</h3>
    <% end %>
<% end %>

app/views/users/_stock_result.js.erb
document.querySelector('#stock-result').innerHTML = '<%= escape_javascript(render 'users/stock_result.html') %>'

app/views/users/_user.html.erb
<h2>User Details</h2>

<h3>Name: <%= @user.name %>: <%= @user.id %></h3>
<h3>Email: <%= @user.email %></h3>
<h3>Username: <%= @user.username %></h3>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1 align="center">Edit User</h1>

<%= render 'users/form' %>

<%= render 'users/form_footer' %>

app/views/users/index.html.erb
<h1 align="center">Our Investors!</h1>

<h1 align="center">Find other investors!</h1>
<h1 align="center"><%= link_to "Home", root_path %></h1>

<div align="center">
    <%= form_tag users_path, method: :get do %>
        <%= label_tag :name, "Search by name:" %>
        <%= text_field_tag :name, params[:name], placeholder: "User's Name" %>
        <%= submit_tag 'Search' %>
    <% end %>
</div>

<div align="center">
    <%= form_tag users_path, method: :get do %>
        <%= label_tag :email, "Search by email:" %>
        <%= text_field_tag :email, params[:email], placeholder: "User's Email" %>
        <%= submit_tag 'Search'  %>
    <% end %>
</div>

<div align="center">
    <%= form_tag users_path, method: :get do %>
        <%= label_tag :username, "Search by username:" %>
        <%= text_field_tag :username, params[:username], placeholder: "Username" %>
        <%= submit_tag "Search" %>
    <% end %>
</div>

<div align="center">
    <% if @user %>
        <%= render 'user' %>
    <% end %>
</div>

<div align="center">
    <%= render partial: 'list_users' %>
</div>

<%= link_to "Home", root_path %>
<%= link_to "Create New User", new_user_path %>
<%= link_to "Stocks", search_stocks_path %>

app/views/users/my_friends.html.erb
<h1 align="center">Connect With Friends!</h1>

<div align="center">
    <%= form_tag search_users_path, remote: true, method: :get do %>
        <%= label_tag :potential_friend, "Enter name or email:" %>
        <%= text_field_tag :potential_friend, params[:potential_friend], placeholder: "Name or email" %>
        
        <%= submit_tag "Connect" %>
    <% end %>
</div>

<div align="center">
    <% if @user %>
        <%= render partial: 'list_users' %>
    <% end %>
</div> 

<div align="center" id="friend-result"> 

</div> 

<% if !@friendships.nil? %>
<h1 align="center">My Friends</h1> 
    <table align="center", class="table table-striped col-md-6">
        <tr>
            <th>Name</th>
            <th>Email</th>
        </tr>
    
        
            <% @friendships.each do |friend| %>
                <tr>
                    <td><%= link_to friend.name, user_path(friend) %></td>
                    <td><%= friend.email %></td>
                    <td><%= link_to "Remove Friend", friendship_path(friend),
                            method: :delete, data: { confirm: "Are you sure?" } %></td>
                </tr>
            <% end %>
        
    </table>
<% end %>
    

app/views/users/portfolio.html.erb
<h1 align="center">Search for Stocks here</h1>

<div align="center">
    <%= form_tag search_stocks_path, remote: true, method: :get do %>
        <%= label_tag :stock, "Search Stocks:" %>
        <%= text_field_tag :stock, params[:stock], placeholder: "Ticker Symbol" %>
        
        <%= submit_tag "Search" %>
    <% end %>
</div>

<% if logged_in? %>
    <div align="center" id="stock-result">
       
    </div>
<% else %>
    <div align="center">
        <h1>Please log in to search and follow stocks</h1>
        <h1><%= link_to "Log In", login_path %></h1>
    
<% end %>

<%= link_to "Home", root_path %>

app/views/users/show.html.erb
<div align="center">
    <h1><%= @user.name %>'s Profile</h1>
    
    <h3><%= @user.username %></h3>
    <h3><%= @user.name %></h3>
    <h3><%= @user.email %></h3> 
    <h2>Balance: $<%= @user.balance %></h3>
    
    <h5>My Stocks</h5>

    <% if @user.stocks.any? %> 
        <div class="row"> 
            <%= render partial: "users/list_stocks" %> 
        </div> 
    <% end %>
    
    <%= render 'users/friends' %> 
    <h3><%= link_to "Make Friends", users_path %> </h3>
    
    <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Edit Profile", edit_user_path(@user) %></li>
        <li><%= link_to "Delete Profile", user_path(@user), 
                                          method: :delete, data: { confirm: "Are you sure?" } %></li>
    </ul>
</div>