config/routes.rb
Rails.application.routes.draw do



  resources :line_items
  resources :carts
  get 'signup', to: "users#new"
  get 'login', to: "sessions#new", as: "login"
  post 'login', to: "sessions#create" 
  get 'logout', to: "sessions#destroy", as: "logout"

  root to: "welcome#index"

  resources :user_stocks, only: [:create, :destroy]
  resources :users 
  resources :friendships
  
  get 'search_users', to: "users#search_users"
  get 'my_friends', to: "users#my_friends"
  get 'search_stocks', to: "stocks#search"
  get 'portfolio', to: "users#portfolio"
  post 'add_friend', to: "users#add_friend" 

  mount ActionCable.server, at: '/cable'

  get 'chat', to: "chatroom#index", as: "chatroom"

  post 'message', to: "messages#create"

end 

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="jumbotron bg-light">

  <div align="center">
    <% if logged_in? %>
        <%= link_to "Make Friends", "#", class: "btn btn-success" %>
        <%= link_to "Find Stocks", portfolio_path, class: "btn btn-success" %>
    <% else %>
        <%= link_to "Sign up Now!", signup_path, class: "btn btn-success" %> 
        <%= link_to "Log In", login_path, class: "btn btn-success" %> 
    <% end %>
</div>

</div>




<div align="center">
    <%= link_to "All Investors", users_path %>
    <%= link_to "Create New User", new_user_path %>
    <%= link_to "Stocks", search_stocks_path %>
</div>