config/routes.rb
Rails.application.routes.draw do



  resources :line_items
  resources :carts
  get 'signup', to: "users#new"
  get 'login', to: "sessions#new", as: "login"
  post 'login', to: "sessions#create" 
  get 'logout', to: "sessions#destroy", as: "logout"

  root to: "welcome#index"

  resources :user_stocks, only: [:create, :destroy]
  resources :users 
  resources :friendships
  
  get 'search_users', to: "users#search_users"
  get 'my_friends', to: "users#my_friends"
  get 'search_stocks', to: "stocks#search"
  get 'portfolio', to: "users#portfolio"
  post 'add_friend', to: "users#add_friend" 

  mount ActionCable.server, at: '/cable'

  get 'chat', to: "chatroom#index", as: "chatroom"

  post 'message', to: "messages#create"

end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord 
    
end

app/models/friendship.rb
class Friendship < ApplicationRecord
    belongs_to :user
    belongs_to :friend, :class_name => "User"
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :stock
  belongs_to :cart
end

app/models/message.rb
class Message < ApplicationRecord 
    belongs_to :user
end

app/models/stock.rb
class Stock < ApplicationRecord
    has_many :user_stocks, dependent: :destroy
    has_many :users, through: :user_stocks 
    
    
    def self.find_stock(ticker)
        begin
             client = IEX::Api::Client.new(publishable_token: 'pk_3663767343b64e9886356a14077c3f2c')
             new_stock = client.quote(ticker)
             self.new(name: new_stock.company_name, ticker: new_stock.symbol, 
                 market_cap: new_stock.market_cap, last_price: new_stock.latest_price,
                 sector: new_stock.sector, high: new_stock.high, low: new_stock.low,
                 pe_ratio: new_stock.pe_ratio, ytd_change: new_stock.ytd_change)
        rescue Exception => e
             return nil
        end
       
    end
    
    def self.find_by_ticker(ticker)
        #where("ticker LIKE ?", "%#{ticker}%").first
        where(ticker: ticker).first
    end 

     
    
    
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :remember_token 
    has_many :messages 
    has_many :friendships
    has_many :friends, through: :friendships
    has_many :user_stocks, dependent: :destroy
    has_many :stocks, through: :user_stocks 
    
    has_secure_password
    
    validates :name, :username, :email, presence: true
    validates :username, uniqueness: true
    validates :email, length: { minimum: 8 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, length: { maximum: 100 }, 
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }
            
    def self.search_by_email(email)
         where("email LIKE ?", "%#{email}%") 
         begin
            user = User.find_by(email: email)
            new(name: user.name, email: user.email, username: user.username)
         rescue Exception => e
            return nil
            
         end
    end 

    def self.youbank_welcome(name) 
        user = User.find_by(name: name) 
        "#{user}! #{YouBank.welcome}"
    end 
    
    def self.search_by_name(name)
        where("name LIKE ?", "%#{name}%")
        begin
            user = User.find_by(name: name)
            new(name: user.name, email: user.email, username: user.username)
        rescue Exception => e
            return nil
        end
    
    end
    
    def self.search_by_username(username)
        where("username LIKE ?", "%#{username}%")
        begin
            user = User.find_by(username: username)
            new(name: user.name, email: user.email, username: user.username)
        rescue Exception => e
            return nil
        end
    end
    
    def stock_added?(ticker)
        stock = Stock.find_by_ticker(ticker)
        return false unless stock
        user_stocks.where(stock_id: stock.id).exists?
    end
    
    def under_stock_limit?
        (user_stocks.count < 10)
    end
    
    def can_add_stock?(ticker)
        under_stock_limit? && !stock_added?(ticker)
    end 

    def stock_purchase_price(ticker, quantity) 
        stock = Stock.find_by_ticker(ticker)
        total_price = stock.latest_price * quantity 
        total_price
    end
    
    def self.search(param)
        cleaned_param = clean_parameter(param)
        result = (match_name(param) + match_username(param) +
                 match_email(param)).uniq
        return nil unless result
        result
    end

    def self.clean_parameter(param)
        param.strip!
        param.downcase!
    end
    
    #try to combione match_* methods below into 1 method 

    def self.match_name(name)
        self.where("name LIKE ?", "%#{name}%")
    end
    
    def self.match_email(email)
        self.where("email LIKE ?", "%#{email}%")
    end
    
    def self.match_username(username)
        self.where("username LIKE ?", "%#{username}%")
    end
    
    
    
    def not_yet_friends?(user)
        friendships.where(friend_id: user).count < 1
    end
    
    def User.digest(string)
        Digest::SHA2.hexdigest(string)
    end
    
    
    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
    belongs_to :user
    belongs_to :stock
    
    def update_balance 

    end 
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
    
   
    
end

app/helpers/carts_helper.rb
module CartsHelper 
    private 

    def set_cart 
        if @cart 
            @cart = Cart.find(session[:cart_id]) 
        else 
            @cart = Cart.create 
            session[:cart_id] = @cart.id 
        end 
    end 
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
    def log_in(user)
        session[:user_id] = user.id
    end
    
    def log_out
      session[:user_id] = nil
      @current_user = nil
    end
    
    def logged_in?
        !current_user.nil?
    end
    
    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-blue bg-light">
  <%= link_to "Stockologie", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup"> 
    
    <div class="navbar-nav"> 
      <%= link_to "Stock search", search_stocks_path, class: "nav-item nav-link active" %>
      <%= link_to "All Users", users_path, class: "nav-item nav-link active" %>
      <% if logged_in? %>
        <%= link_to "#{current_user.name.capitalize}'s Accounts", "#", class: "nav-item nav-link" %>
        <%= link_to "#{current_user.name.capitalize}'s Friends", my_friends_path, class: "nav-item nav-link" %>
        
        <%= link_to "Chatroom", chatroom_path, class: "nav-item nav-link" %> 
        <div class="nav-item nav-link float-right">Logged In As: <%= link_to current_user.username.capitalize, user_path(current_user) %></div> <%= link_to "Log Out", logout_path, class: "nav-item nav-link float-right" %>  
      <% else %>
        <%= link_to "Banking", "#", class: "nav-item nav-link" %>
        <%= link_to "Sign Up", signup_path, class: "nav-item nav-link" %>
        <%= link_to "Log In", login_path, class: "nav-item nav-link" %>
        
      <% end %>
    </div> 
    
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <%= csrf_meta_tags %> 
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>
  
  <%= render 'layouts/navigation' %>
  <body>
    
    <% flash.each do |type, message| %>
      <h3><%= message %></h3>
    <% end %>
    
    <%= yield %>
    
  </body>
</html>